name: build and deploy aws 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1






  pushtoacr:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
  deploytoEKS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      
      
      
      
      
      
      
